#!/bin/bash
# Enhanced Swiss Ephemeris Download Script
# Generated by Planetary Accuracy Validator

echo "🌟 Downloading Enhanced Swiss Ephemeris Files..."

cd "/Users/richardbelll/Astrova/backend/ephemeris/"

# Essential files for high accuracy (1800-2200 CE)
declare -a files=(
    "https://www.astro.com/ftp/swisseph/ephe/sepl_06.se1"
    "https://www.astro.com/ftp/swisseph/ephe/sepl_12.se1"
    "https://www.astro.com/ftp/swisseph/ephe/sepl_18.se1"
    "https://www.astro.com/ftp/swisseph/ephe/semo_06.se1"
    "https://www.astro.com/ftp/swisseph/ephe/semo_12.se1"
    "https://www.astro.com/ftp/swisseph/ephe/semo_18.se1"
    "https://www.astro.com/ftp/swisseph/ephe/seas_06.se1"
    "https://www.astro.com/ftp/swisseph/ephe/seas_12.se1"
    "https://www.astro.com/ftp/swisseph/ephe/seas_18.se1"
)

for url in "${files[@]}"; do
    filename=$(basename "$url")
    echo "⬇️  Downloading $filename..."
    curl -L -o "$filename" "$url"
    if [ $? -eq 0 ]; then
        echo "✅ $filename downloaded successfully"
    else
        echo "❌ Failed to download $filename"
    fi
done

echo "🎉 Enhanced ephemeris download completed!"
